### ISSUE TITLE
Colors not persisting, or being used on new visits

### ISSUE THREAD

**Issue by evitalis** [gulaschskanone/ep_brightcolorpicker#1]
I have noticed using the current version of this plugin that when openign a pad the color is still randomly chosen from outside of this palette. When the pad is saved it discards the colors chosen so the next visit it does not have colors. These normally both are non-issues with the standard color picker from what I can tell as they will persist even between visits.

I have edited the settings.json as described as well.

**Comment by gulaschskanone** [comment]
Thanks for your message. Both should be able to solve. 
Feel free to commit a solution.

**Comment by evitalis** [comment]
I am not good with javascript or nodejs so I would be unsure where to start with this. I even did test reinstalling the plugin though and adding the settings to setting.js.

**Comment by gulaschskanone** [comment]
Did you use IE for writing?

**Comment by evitalis** [comment]
Sorry for the delay in update. No I use the newest version of Firefox. I can test with the newest release of Opera later today if needed.

**Comment by gulaschskanone** [comment]
I had noticed the problem is independently from the browser used. 
Unfortunally I have no idea yet. I asked for help in issue 151 (etherpad).

**Comment by evitalis** [comment]
I just got around to testing this. I had permission errors updating and removing the plugin but when moving to 0.0.7 I still get a color not on the palette when first opening/creating a pad.
